export const presetThemes = [
  {
    name: "Minimal",
    theme: {
      bgPage: "#ffffff",
      textPrimary: "#111827",
      textSecondary: "#6b7280",
      textTertiary: "#4b5563",
      headerGradientStart: "#6366f1",
      headerGradientEnd: "#8b5cf6",
      profileBorder: "#ffffff",
      profileBg: "#ffffff",
      socialBg: "#ffffff",
      socialDefault: "#6b7280",
      socialGithub: "#181717",
      socialLinkedin: "#0a66c2",
      socialTwitter: "#1da1f2",
      socialYoutube: "#ff0000",
      socialInstagram: "#e4405f",
      socialFacebook: "#1877f2",
      linkCardBg: "#ffffff",
      linkCardText: "#111827",
      linkCardTextSecondary: "#6b7280",
      linkCardIcon: "#8b5cf6",
      linkCardRadius: "12px",
      linkThumbnailBg: "#f3f4f6",
      footerText: "#9ca3af",
    },
  },
  {
    name: "Twilight",
    theme: {
      bgPage: "#1f2937",
      textPrimary: "#f9fafb",
      textSecondary: "#d1d5db",
      textTertiary: "#9ca3af",
      headerGradientStart: "#7c3aed",
      headerGradientEnd: "#a855f7",
      profileBorder: "#f9fafb",
      profileBg: "#374151",
      socialBg: "#374151",
      socialDefault: "#d1d5db",
      socialGithub: "#f9fafb",
      socialLinkedin: "#0a66c2",
      socialTwitter: "#1da1f2",
      socialYoutube: "#ff0000",
      socialInstagram: "#e4405f",
      socialFacebook: "#1877f2",
      linkCardBg: "#374151",
      linkCardText: "#f9fafb",
      linkCardTextSecondary: "#d1d5db",
      linkCardIcon: "#a855f7",
      linkCardRadius: "12px",
      linkThumbnailBg: "#4b5563",
      footerText: "#9ca3af",
    },
  },
  {
    name: "Cosmic Purple",
    theme: {
      bgPage: "#0F172A",
      textPrimary: "#FFFFFF",
      textSecondary: "#A5B4FC",
      textTertiary: "#818CF8",
      headerGradientStart: "#4F46E5",
      headerGradientEnd: "#7C3AED",
      profileBorder: "rgba(165, 180, 252, 0.2)",
      profileBg: "rgba(15, 23, 42, 0.7)",
      socialBg: "rgba(79, 70, 229, 0.1)",
      socialDefault: "#A5B4FC",
      socialGithub: "#A5B4FC",
      socialLinkedin: "#A5B4FC",
      socialTwitter: "#A5B4FC",
      socialYoutube: "#A5B4FC",
      socialInstagram: "#A5B4FC",
      socialFacebook: "#A5B4FC",
      linkCardBg: "rgba(30, 41, 59, 0.5)",
      linkCardText: "#E0E7FF",
      linkCardTextSecondary: "#818CF8",
      linkCardIcon: "#818CF8",
      linkCardRadius: "16px",
      linkThumbnailBg: "rgba(99, 102, 241, 0.1)",
      footerText: "#64748B",
    },
  },
  {
    name: "Desert",
    theme: {
      bgPage: "#fff7ed",
      textPrimary: "#78350f",
      textSecondary: "#92400e",
      textTertiary: "#d97706",
      headerGradientStart: "#f59e0b",
      headerGradientEnd: "#fbbf24",
      profileBorder: "#d97706",
      profileBg: "#ffedd5",
      socialBg: "#ffedd5",
      socialDefault: "#92400e",
      socialGithub: "#78350f",
      socialLinkedin: "#0a66c2",
      socialTwitter: "#1da1f2",
      socialYoutube: "#ff0000",
      socialInstagram: "#e4405f",
      socialFacebook: "#1877f2",
      linkCardBg: "#fed7aa",
      linkCardText: "#78350f",
      linkCardTextSecondary: "#92400e",
      linkCardIcon: "#d97706",
      linkCardRadius: "12px",
      linkThumbnailBg: "#fdba74",
      footerText: "#92400e",
    },
  },
  {
    name: "Blush",
    theme: {
      bgPage: "#fff1f2",
      textPrimary: "#831843",
      textSecondary: "#9d174d",
      textTertiary: "#ec4899",
      headerGradientStart: "#f472b6",
      headerGradientEnd: "#fb7185",
      profileBorder: "#ec4899",
      profileBg: "#fce7f3",
      socialBg: "#fce7f3",
      socialDefault: "#9d174d",
      socialGithub: "#831843",
      socialLinkedin: "#0a66c2",
      socialTwitter: "#1da1f2",
      socialYoutube: "#ff0000",
      socialInstagram: "#e4405f",
      socialFacebook: "#1877f2",
      linkCardBg: "#fbcfe8",
      linkCardText: "#831843",
      linkCardTextSecondary: "#9d174d",
      linkCardIcon: "#ec4899",
      linkCardRadius: "12px",
      linkThumbnailBg: "#f9a8d4",
      footerText: "#9d174d",
    },
  },
    {
    name: "CosmicIndigo",
    theme: {
      bgPage: "#0F172A", // Main dark indigo background
      textPrimary: "#F5F6FF", // Primary text (headings, main content)
      textSecondary: "#A5B4FC", // Secondary text (subtitles, links)
      textTertiary: "#818CF8", // Tertiary text (minor text, placeholders)
      headerGradientStart: "#4F46E5", // Gradient start for headers (hero, navbar)
      headerGradientEnd: "#6366F1", // Gradient end for headers
      profileBorder: "#4F46E5", // Profile border (e.g., navbar avatar)
      profileBg: "#312E81", // Profile background (frosted-glass effect)
      socialBg: "#312E81", // Social icon background
      socialDefault: "#A5B4FC", // Default social icon color
      socialGithub: "#181717", // GitHub icon color
      socialLinkedin: "#0A66C2", // LinkedIn icon color
      socialTwitter: "#1DA1F2", // Twitter/X icon color
      socialYoutube: "#FF0000", // YouTube icon color
      socialInstagram: "#E4405F", // Instagram icon color
      socialFacebook: "#1877F2", // Facebook icon color
      linkCardBg: "#312E81", // Link card background (frosted-glass)
      linkCardText: "#F5F6FF", // Link card primary text
      linkCardTextSecondary: "#A5B4FC", // Link card secondary text
      linkCardIcon: "#4F46E5", // Link card icon color
      linkCardRadius: "16px", // Link card border radius
      linkThumbnailBg: "#1E293B", // Thumbnail background
      footerText: "#A5B4FC", // Footer text color
    },
  },
  {
    name: "StellarIndigo",
    theme: {
      bgPage: "#0F172A", // Same dark indigo background
      textPrimary: "#F5F6FF", // Primary text
      textSecondary: "#A5B4FC", // Secondary text
      textTertiary: "#A5B4FC", // Tertiary text (slightly brighter)
      headerGradientStart: "#6366F1", // Softer gradient start
      headerGradientEnd: "#7C3AED", // Purple accent for gradient end
      profileBorder: "#6366F1", // Softer indigo border
      profileBg: "#3730A3", // Slightly lighter frosted-glass
      socialBg: "#3730A3", // Matching social background
      socialDefault: "#A5B4FC", // Default social color
      socialGithub: "#181717",
      socialLinkedin: "#0A66C2",
      socialTwitter: "#1DA1F2",
      socialYoutube: "#FF0000",
      socialInstagram: "#E4405F",
      socialFacebook: "#1877F2",
      linkCardBg: "#3730A3", // Lighter link card background
      linkCardText: "#F5F6FF", // Link card text
      linkCardTextSecondary: "#A5B4FC", // Secondary text
      linkCardIcon: "#6366F1", // Softer icon color
      linkCardRadius: "12px", // Tighter radius for modern look
      linkThumbnailBg: "#1E293B", // Same thumbnail background
      footerText: "#A5B4FC", // Footer text
    },
  },
  {
    name: "NebulaIndigo",
    theme: {
      bgPage: "#0F172A", // Consistent dark indigo
      textPrimary: "#F5F6FF", // Primary text
      textSecondary: "#A5B4FC", // Secondary text
      textTertiary: "#818CF8", // Tertiary text
      headerGradientStart: "#4F46E5", // Bold gradient start
      headerGradientEnd: "#A78BFA", // Lighter purple end
      profileBorder: "#A78BFA", // Light purple border
      profileBg: "#4338CA", // Brighter frosted-glass
      socialBg: "#4338CA", // Matching social background
      socialDefault: "#A5B4FC", // Default social color
      socialGithub: "#181717",
      socialLinkedin: "#0A66C2",
      socialTwitter: "#1DA1F2",
      socialYoutube: "#FF0000",
      socialInstagram: "#E4405F",
      socialFacebook: "#1877F2",
      linkCardBg: "#4338CA", // Brighter link card background
      linkCardText: "#F5F6FF", // Link card text
      linkCardTextSecondary: "#A5B4FC", // Secondary text
      linkCardIcon: "#A78BFA", // Light purple icon
      linkCardRadius: "20px", // Softer radius for organic feel
      linkThumbnailBg: "#1E293B", // Thumbnail background
      footerText: "#A5B4FC", // Footer text
    },
  },
  {
    name: "Frost",
    theme: {
      bgPage: "#f4f9ff",
      textPrimary: "#1e3a8a",
      textSecondary: "#1e40af",
      textTertiary: "#3b82f6",
      headerGradientStart: "#60a5fa",
      headerGradientEnd: "#93c5fd",
      profileBorder: "#3b82f6",
      profileBg: "#dbeafe",
      socialBg: "#dbeafe",
      socialDefault: "#1e40af",
      socialGithub: "#1e3a8a",
      socialLinkedin: "#0a66c2",
      socialTwitter: "#1da1f2",
      socialYoutube: "#ff0000",
      socialInstagram: "#e4405f",
      socialFacebook: "#1877f2",
      linkCardBg: "#bfdbfe",
      linkCardText: "#1e3a8a",
      linkCardTextSecondary: "#1e40af",
      linkCardIcon: "#3b82f6",
      linkCardRadius: "12px",
      linkThumbnailBg: "#93c5fd",
      footerText: "#1e40af",
    },
  },
  {
    name: "Crimson",
    theme: {
      bgPage: "#fef2f2",
      textPrimary: "#991b1b",
      textSecondary: "#b91c1c",
      textTertiary: "#ef4444",
      headerGradientStart: "#dc2626",
      headerGradientEnd: "#f87171",
      profileBorder: "#ef4444",
      profileBg: "#fee2e2",
      socialBg: "#fee2e2",
      socialDefault: "#b91c1c",
      socialGithub: "#991b1b",
      socialLinkedin: "#0a66c2",
      socialTwitter: "#1da1f2",
      socialYoutube: "#ff0000",
      socialInstagram: "#e4405f",
      socialFacebook: "#1877f2",
      linkCardBg: "#fecaca",
      linkCardText: "#991b1b",
      linkCardTextSecondary: "#b91c1c",
      linkCardIcon: "#ef4444",
      linkCardRadius: "12px",
      linkThumbnailBg: "#f87171",
      footerText: "#b91c1c",
    },
  },
  {
    name: "Slate",
    theme: {
      bgPage: "#f1f5f9",
      textPrimary: "#1e293b",
      textSecondary: "#475569",
      textTertiary: "#64748b",
      headerGradientStart: "#94a3b8",
      headerGradientEnd: "#cbd5e1",
      profileBorder: "#64748b",
      profileBg: "#e2e8f0",
      socialBg: "#e2e8f0",
      socialDefault: "#475569",
      socialGithub: "#1e293b",
      socialLinkedin: "#0a66c2",
      socialTwitter: "#1da1f2",
      socialYoutube: "#ff0000",
      socialInstagram: "#e4405f",
      socialFacebook: "#1877f2",
      linkCardBg: "#e2e8f0",
      linkCardText: "#1e293b",
      linkCardTextSecondary: "#475569",
      linkCardIcon: "#64748b",
      linkCardRadius: "12px",
      linkThumbnailBg: "#cbd5e1",
      footerText: "#475569",
    },
  },
  {
    name: "Lime",
    theme: {
      bgPage: "#f7fee7",
      textPrimary: "#365314",
      textSecondary: "#4d7c0f",
      textTertiary: "#84cc16",
      headerGradientStart: "#a3e635",
      headerGradientEnd: "#bef264",
      profileBorder: "#84cc16",
      profileBg: "#ecfccb",
      socialBg: "#ecfccb",
      socialDefault: "#4d7c0f",
      socialGithub: "#365314",
      socialLinkedin: "#0a66c2",
      socialTwitter: "#1da1f2",
      socialYoutube: "#ff0000",
      socialInstagram: "#e4405f",
      socialFacebook: "#1877f2",
      linkCardBg: "#d9f99d",
      linkCardText: "#365314",
      linkCardTextSecondary: "#4d7c0f",
      linkCardIcon: "#84cc16",
      linkCardRadius: "12px",
      linkThumbnailBg: "#bef264",
      footerText: "#4d7c0f",
    },
  },
  {
    name: "Violet",
    theme: {
      bgPage: "#faf5ff",
      textPrimary: "#4c1d95",
      textSecondary: "#6d28d9",
      textTertiary: "#a855f7",
      headerGradientStart: "#c084fc",
      headerGradientEnd: "#d8b4fe",
      profileBorder: "#a855f7",
      profileBg: "#f3e8ff",
      socialBg: "#f3e8ff",
      socialDefault: "#6d28d9",
      socialGithub: "#4c1d95",
      socialLinkedin: "#0a66c2",
      socialTwitter: "#1da1f2",
      socialYoutube: "#ff0000",
      socialInstagram: "#e4405f",
      socialFacebook: "#1877f2",
      linkCardBg: "#e9d5ff",
      linkCardText: "#4c1d95",
      linkCardTextSecondary: "#6d28d9",
      linkCardIcon: "#a855f7",
      linkCardRadius: "12px",
      linkThumbnailBg: "#d8b4fe",
      footerText: "#6d28d9",
    },
  },
  {
    name: "Amber",
    theme: {
      bgPage: "#fefce8",
      textPrimary: "#713f12",
      textSecondary: "#854d0e",
      textTertiary: "#eab308",
      headerGradientStart: "#facc15",
      headerGradientEnd: "#fde047",
      profileBorder: "#eab308",
      profileBg: "#fef9c3",
      socialBg: "#fef9c3",
      socialDefault: "#854d0e",
      socialGithub: "#713f12",
      socialLinkedin: "#0a66c2",
      socialTwitter: "#1da1f2",
      socialYoutube: "#ff0000",
      socialInstagram: "#e4405f",
      socialFacebook: "#1877f2",
      linkCardBg: "#fef08a",
      linkCardText: "#713f12",
      linkCardTextSecondary: "#854d0e",
      linkCardIcon: "#eab308",
      linkCardRadius: "12px",
      linkThumbnailBg: "#fde047",
      footerText: "#854d0e",
    },
  },
  {
    name: "Sky",
    theme: {
      bgPage: "#f0f9ff",
      textPrimary: "#0c4a6e",
      textSecondary: "#155e75",
      textTertiary: "#38bdf8",
      headerGradientStart: "#0ea5e9",
      headerGradientEnd: "#7dd3fc",
      profileBorder: "#38bdf8",
      profileBg: "#e0f2fe",
      socialBg: "#e0f2fe",
      socialDefault: "#155e75",
      socialGithub: "#0c4a6e",
      socialLinkedin: "#0a66c2",
      socialTwitter: "#1da1f2",
      socialYoutube: "#ff0000",
      socialInstagram: "#e4405f",
      socialFacebook: "#1877f2",
      linkCardBg: "#bae6fd",
      linkCardText: "#0c4a6e",
      linkCardTextSecondary: "#155e75",
      linkCardIcon: "#38bdf8",
      linkCardRadius: "12px",
      linkThumbnailBg: "#7dd3fc",
      footerText: "#155e75",
    },
  },
  {
    name: "Midnight",
    theme: {
      bgPage: "#0f172a",
      textPrimary: "#f1f5f9",
      textSecondary: "#cbd5e1",
      textTertiary: "#94a3b8",
      headerGradientStart: "#334155",
      headerGradientEnd: "#1e293b",
      profileBorder: "#1e293b",
      profileBg: "#334155",
      socialBg: "#1e293b",
      socialDefault: "#94a3b8",
      socialGithub: "#f1f5f9",
      socialLinkedin: "#7dd3fc",
      socialTwitter: "#38bdf8",
      socialYoutube: "#f87171",
      socialInstagram: "#f472b6",
      socialFacebook: "#60a5fa",
      linkCardBg: "#1e293b",
      linkCardText: "#f1f5f9",
      linkCardTextSecondary: "#cbd5e1",
      linkCardIcon: "#7dd3fc",
      linkCardRadius: "12px",
      linkThumbnailBg: "#334155",
      footerText: "#64748b",
    },
  },
  {
    name: "Emerald",
    theme: {
      bgPage: "#ecfdf5",
      textPrimary: "#064e3b",
      textSecondary: "#065f46",
      textTertiary: "#10b981",
      headerGradientStart: "#34d399",
      headerGradientEnd: "#10b981",
      profileBorder: "#10b981",
      profileBg: "#6ee7b7",
      socialBg: "#d1fae5",
      socialDefault: "#047857",
      socialGithub: "#064e3b",
      socialLinkedin: "#0e7490",
      socialTwitter: "#0891b2",
      socialYoutube: "#dc2626",
      socialInstagram: "#db2777",
      socialFacebook: "#2563eb",
      linkCardBg: "#a7f3d0",
      linkCardText: "#064e3b",
      linkCardTextSecondary: "#065f46",
      linkCardIcon: "#047857",
      linkCardRadius: "12px",
      linkThumbnailBg: "#6ee7b7",
      footerText: "#047857",
    },
  },
  {
    name: "Sunset",
    theme: {
      bgPage: "#fef2f2",
      textPrimary: "#7f1d1d",
      textSecondary: "#991b1b",
      textTertiary: "#ef4444",
      headerGradientStart: "#f97316",
      headerGradientEnd: "#ef4444",
      profileBorder: "#ef4444",
      profileBg: "#fca5a5",
      socialBg: "#fee2e2",
      socialDefault: "#b91c1c",
      socialGithub: "#7f1d1d",
      socialLinkedin: "#0369a1",
      socialTwitter: "#0ea5e9",
      socialYoutube: "#dc2626",
      socialInstagram: "#db2777",
      socialFacebook: "#1d4ed8",
      linkCardBg: "#fecaca",
      linkCardText: "#7f1d1d",
      linkCardTextSecondary: "#991b1b",
      linkCardIcon: "#b91c1c",
      linkCardRadius: "12px",
      linkThumbnailBg: "#fca5a5",
      footerText: "#b91c1c",
    },
  },
  {
    name: "Ocean",
    theme: {
      bgPage: "#f0f9ff",
      textPrimary: "#083344",
      textSecondary: "#164e63",
      textTertiary: "#0ea5e9",
      headerGradientStart: "#0ea5e9",
      headerGradientEnd: "#0369a1",
      profileBorder: "#0ea5e9",
      profileBg: "#7dd3fc",
      socialBg: "#e0f2fe",
      socialDefault: "#0c4a6e",
      socialGithub: "#083344",
      socialLinkedin: "#0369a1",
      socialTwitter: "#0284c7",
      socialYoutube: "#dc2626",
      socialInstagram: "#db2777",
      socialFacebook: "#1d4ed8",
      linkCardBg: "#bae6fd",
      linkCardText: "#083344",
      linkCardTextSecondary: "#164e63",
      linkCardIcon: "#0c4a6e",
      linkCardRadius: "12px",
      linkThumbnailBg: "#7dd3fc",
      footerText: "#0c4a6e",
    },
  },
  {
    name: "Custom",
    theme: null,
  },
];
